package io.openems.edge.matter.meter;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
		name = "Matter Electricity Meter", //
		description = "Maps a Matter device with Electrical Measurement capabilities to an OpenEMS Electricity Meter.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Meter-Type", description = "Grid, Production, Consumption")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "Matter Bridge ID", description = "ID of the Matter Bridge component")
	String matter_id() default "matter0";

	@AttributeDefinition(name = "Matter Node ID", description = "The Matter node ID of the commissioned device")
	long matterNodeId();

	@AttributeDefinition(name = "Matter Endpoint ID", description = "The endpoint ID on the Matter device")
	int matterEndpointId() default 1;

	@AttributeDefinition(name = "Matter Bridge target filter", description = "This is auto-generated by 'Matter Bridge ID'.")
	String Matter_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Matter Electricity Meter [{id}]";
}
